### PR TITLE
Add support for userland classname and style props

### PR DESCRIPTION
**Pull request by georgegillams**

### CODE REVIEW

**Comment by tiendq** [comment]
I'm pretty busy now, I'll look at in next few days.

Thanks,

**Comment by georgegillams** [comment]
Any update on this? It would be nice to change my dependency to point to the original instead of my fork. If there's anything you want me to do give me a shout 👍

**Comment by tiendq** [comment]
There was a bug with width/height calculation in your commit. I fixed it.

A new version was published, please give it a try.

Thanks,

**Comment by georgegillams** [comment]
Yeah that's perfect. Thanks! 👍

**Pull request merged**
